= Create Steps for Scenarios

. Start the app with the following command in the Terminal (within Visual Studio Code):
+
 npm start
+
. Create the link:../steps/navigation.steps.feature[navigation] step.
. Use the 'debug' feature to navigate to the page.

====
*How to Use the 'Debug' Feature?*

. Hold down the `ctrl` key. This turns the step in the Feature File into a link. Click on the step.
. This will take you to the step in the `Step Definition` file.
. In the last 

Don't forget to ensure you're running the correct `Debug` configuration.

====

Use the `@runThis` tag on the scenario to run it.

====
*Common Problems*

. `@runThis` tag not in the `protractor.debug.config.ts` <LINK NEEDED HERE> file 

====

. Check the steps files to see if a step you need already exits:


. If the step already exists, follow the steps in the next chapter called `Using an Exisiting Step`. If you have to create a new one, read the `Creating a New Step` chapter.

== Using an Exisitng Step

Copy and paste it into your scenario

. Create Locators.

Locators are in the link:../quote-engine-e2e/src/pages/[pages] folder  . Find the correct page.

Page names are in the link:../libs/enums/src/lib/page-url.enum.ts[page-url.enum.ts] file

`ctrl + p` to search the Test Automation Framework.